//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCComu
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class VentanillaWSFault
    {
        
        private int faultCodeField;
        
        private string faultMessageField;
        
        private string categoryField;
        
        private string[] possibleSolutionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int faultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultMessage
        {
            get
            {
                return this.faultMessageField;
            }
            set
            {
                this.faultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("possibleSolutions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] possibleSolutions
        {
            get
            {
                return this.possibleSolutionsField;
            }
            set
            {
                this.possibleSolutionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws")]
    public partial class adjunto
    {
        
        private string filenameField;
        
        private byte[] contentField;
        
        private bool compressedField;
        
        private bool compressedFieldSpecified;
        
        private bool signedField;
        
        private bool signedFieldSpecified;
        
        private bool encryptedField;
        
        private bool encryptedFieldSpecified;
        
        private bool processedField;
        
        private bool processedFieldSpecified;
        
        private bool publicField;
        
        private bool publicFieldSpecified;
        
        private string md5Field;
        
        private long contentSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool compressed
        {
            get
            {
                return this.compressedField;
            }
            set
            {
                this.compressedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressedSpecified
        {
            get
            {
                return this.compressedFieldSpecified;
            }
            set
            {
                this.compressedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool signed
        {
            get
            {
                return this.signedField;
            }
            set
            {
                this.signedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signedSpecified
        {
            get
            {
                return this.signedFieldSpecified;
            }
            set
            {
                this.signedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encryptedSpecified
        {
            get
            {
                return this.encryptedFieldSpecified;
            }
            set
            {
                this.encryptedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool processed
        {
            get
            {
                return this.processedField;
            }
            set
            {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processedSpecified
        {
            get
            {
                return this.processedFieldSpecified;
            }
            set
            {
                this.processedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool @public
        {
            get
            {
                return this.publicField;
            }
            set
            {
                this.publicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicSpecified
        {
            get
            {
                return this.publicFieldSpecified;
            }
            set
            {
                this.publicFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string md5
        {
            get
            {
                return this.md5Field;
            }
            set
            {
                this.md5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long contentSize
        {
            get
            {
                return this.contentSizeField;
            }
            set
            {
                this.contentSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Comunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class ComunicacionSimplificada
    {
        
        private long idComunicacionField;
        
        private long cuitDestinatarioField;
        
        private string fechaPublicacionField;
        
        private string fechaVencimientoField;
        
        private long sistemaPublicadorField;
        
        private string sistemaPublicadorDescField;
        
        private int estadoField;
        
        private string estadoDescField;
        
        private string asuntoField;
        
        private int prioridadField;
        
        private bool tieneAdjuntoField;
        
        private string referencia1Field;
        
        private string referencia2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idComunicacion
        {
            get
            {
                return this.idComunicacionField;
            }
            set
            {
                this.idComunicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long cuitDestinatario
        {
            get
            {
                return this.cuitDestinatarioField;
            }
            set
            {
                this.cuitDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaPublicacion
        {
            get
            {
                return this.fechaPublicacionField;
            }
            set
            {
                this.fechaPublicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long sistemaPublicador
        {
            get
            {
                return this.sistemaPublicadorField;
            }
            set
            {
                this.sistemaPublicadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sistemaPublicadorDesc
        {
            get
            {
                return this.sistemaPublicadorDescField;
            }
            set
            {
                this.sistemaPublicadorDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string estadoDesc
        {
            get
            {
                return this.estadoDescField;
            }
            set
            {
                this.estadoDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int prioridad
        {
            get
            {
                return this.prioridadField;
            }
            set
            {
                this.prioridadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool tieneAdjunto
        {
            get
            {
                return this.tieneAdjuntoField;
            }
            set
            {
                this.tieneAdjuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string referencia1
        {
            get
            {
                return this.referencia1Field;
            }
            set
            {
                this.referencia1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string referencia2
        {
            get
            {
                return this.referencia2Field;
            }
            set
            {
                this.referencia2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Comunicacion : ComunicacionSimplificada
    {
        
        private string mensajeField;
        
        private int tiempoDeVidaField;
        
        private adjunto[] adjuntosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tiempoDeVida
        {
            get
            {
                return this.tiempoDeVidaField;
            }
            set
            {
                this.tiempoDeVidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public adjunto[] adjuntos
        {
            get
            {
                return this.adjuntosField;
            }
            set
            {
                this.adjuntosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class RespuestaPaginada
    {
        
        private int paginaField;
        
        private int totalPaginasField;
        
        private int itemsPorPaginaField;
        
        private int totalItemsField;
        
        private ComunicacionSimplificada[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int totalPaginas
        {
            get
            {
                return this.totalPaginasField;
            }
            set
            {
                this.totalPaginasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int itemsPorPagina
        {
            get
            {
                return this.itemsPorPaginaField;
            }
            set
            {
                this.itemsPorPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int totalItems
        {
            get
            {
                return this.totalItemsField;
            }
            set
            {
                this.totalItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ComunicacionSimplificada[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Filter
    {
        
        private System.Nullable<int> estadoField;
        
        private bool estadoFieldSpecified;
        
        private string fechaDesdeField;
        
        private string fechaHastaField;
        
        private System.Nullable<long> comunicacionIdDesdeField;
        
        private bool comunicacionIdDesdeFieldSpecified;
        
        private System.Nullable<long> comunicacionIdHastaField;
        
        private bool comunicacionIdHastaFieldSpecified;
        
        private System.Nullable<bool> tieneAdjuntoField;
        
        private bool tieneAdjuntoFieldSpecified;
        
        private System.Nullable<long> sistemaPublicadorIdField;
        
        private bool sistemaPublicadorIdFieldSpecified;
        
        private int paginaField;
        
        private System.Nullable<int> resultadosPorPaginaField;
        
        private bool resultadosPorPaginaFieldSpecified;
        
        private string referencia1Field;
        
        private string referencia2Field;
        
        public Filter()
        {
            this.paginaField = 1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified
        {
            get
            {
                return this.estadoFieldSpecified;
            }
            set
            {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fechaDesde
        {
            get
            {
                return this.fechaDesdeField;
            }
            set
            {
                this.fechaDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string fechaHasta
        {
            get
            {
                return this.fechaHastaField;
            }
            set
            {
                this.fechaHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<long> comunicacionIdDesde
        {
            get
            {
                return this.comunicacionIdDesdeField;
            }
            set
            {
                this.comunicacionIdDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comunicacionIdDesdeSpecified
        {
            get
            {
                return this.comunicacionIdDesdeFieldSpecified;
            }
            set
            {
                this.comunicacionIdDesdeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<long> comunicacionIdHasta
        {
            get
            {
                return this.comunicacionIdHastaField;
            }
            set
            {
                this.comunicacionIdHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comunicacionIdHastaSpecified
        {
            get
            {
                return this.comunicacionIdHastaFieldSpecified;
            }
            set
            {
                this.comunicacionIdHastaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<bool> tieneAdjunto
        {
            get
            {
                return this.tieneAdjuntoField;
            }
            set
            {
                this.tieneAdjuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tieneAdjuntoSpecified
        {
            get
            {
                return this.tieneAdjuntoFieldSpecified;
            }
            set
            {
                this.tieneAdjuntoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<long> sistemaPublicadorId
        {
            get
            {
                return this.sistemaPublicadorIdField;
            }
            set
            {
                this.sistemaPublicadorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sistemaPublicadorIdSpecified
        {
            get
            {
                return this.sistemaPublicadorIdFieldSpecified;
            }
            set
            {
                this.sistemaPublicadorIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> resultadosPorPagina
        {
            get
            {
                return this.resultadosPorPaginaField;
            }
            set
            {
                this.resultadosPorPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultadosPorPaginaSpecified
        {
            get
            {
                return this.resultadosPorPaginaFieldSpecified;
            }
            set
            {
                this.resultadosPorPaginaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string referencia1
        {
            get
            {
                return this.referencia1Field;
            }
            set
            {
                this.referencia1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string referencia2
        {
            get
            {
                return this.referencia2Field;
            }
            set
            {
                this.referencia2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://core.tecno.afip.gov.ar/model/ws/types")]
    public partial class AuthRequest
    {
        
        private string tokenField;
        
        private string signField;
        
        private long cuitRepresentadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long cuitRepresentada
        {
            get
            {
                return this.cuitRepresentadaField;
            }
            set
            {
                this.cuitRepresentadaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", ConfigurationName="WSCComu.VEConsumer")]
    internal interface VEConsumer
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicaciones", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicacionesR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSCComu.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCComu.consultarComunicacionesResponse> consultarComunicacionesAsync(WSCComu.consultarComunicaciones request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "dores", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "doresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSCComu.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCComu.consultarSistemasPublicadoresResponse> consultarSistemasPublicadoresAsync(WSCComu.consultarSistemasPublicadores request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummy", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DummyResult")]
        System.Threading.Tasks.Task<WSCComu.DummyResult> dummyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacion", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacionResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSCComu.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCComu.consumirComunicacionResponse> consumirComunicacionAsync(WSCComu.consumirComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstados", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstadosResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSCComu.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCComu.consultarEstadosResponse> consultarEstadosAsync(WSCComu.consultarEstados request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarComunicaciones", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    internal partial class consultarComunicaciones
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSCComu.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSCComu.Filter filter;
        
        public consultarComunicaciones()
        {
        }
        
        public consultarComunicaciones(WSCComu.AuthRequest authRequest, WSCComu.Filter filter)
        {
            this.authRequest = authRequest;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarComunicacionesResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    internal partial class consultarComunicacionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        public WSCComu.RespuestaPaginada RespuestaPaginada;
        
        public consultarComunicacionesResponse()
        {
        }
        
        public consultarComunicacionesResponse(WSCComu.RespuestaPaginada RespuestaPaginada)
        {
            this.RespuestaPaginada = RespuestaPaginada;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Sistema
    {
        
        private long idField;
        
        private string descripcionField;
        
        private string certCNsField;
        
        private Subservicio[] subserviciosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certCNs
        {
            get
            {
                return this.certCNsField;
            }
            set
            {
                this.certCNsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Subservicio[] subservicios
        {
            get
            {
                return this.subserviciosField;
            }
            set
            {
                this.subserviciosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Subservicio
    {
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSistemasPublicadores", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    internal partial class consultarSistemasPublicadores
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSCComu.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idSistemaPublicador;
        
        public consultarSistemasPublicadores()
        {
        }
        
        public consultarSistemasPublicadores(WSCComu.AuthRequest authRequest, long idSistemaPublicador)
        {
            this.authRequest = authRequest;
            this.idSistemaPublicador = idSistemaPublicador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSistemasPublicadoresResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    internal partial class consultarSistemasPublicadoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsNullable=false)]
        public WSCComu.Sistema[] Sistemas;
        
        public consultarSistemasPublicadoresResponse()
        {
        }
        
        public consultarSistemasPublicadoresResponse(WSCComu.Sistema[] Sistemas)
        {
            this.Sistemas = Sistemas;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class DummyResult
    {
        
        private string dbserverField;
        
        private string appserverField;
        
        private string authserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dbserver
        {
            get
            {
                return this.dbserverField;
            }
            set
            {
                this.dbserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appserver
        {
            get
            {
                return this.appserverField;
            }
            set
            {
                this.appserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string authserver
        {
            get
            {
                return this.authserverField;
            }
            set
            {
                this.authserverField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consumirComunicacion", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    internal partial class consumirComunicacion
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSCComu.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idComunicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool incluirAdjuntos;
        
        public consumirComunicacion()
        {
        }
        
        public consumirComunicacion(WSCComu.AuthRequest authRequest, long idComunicacion, bool incluirAdjuntos)
        {
            this.authRequest = authRequest;
            this.idComunicacion = idComunicacion;
            this.incluirAdjuntos = incluirAdjuntos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consumirComunicacionResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    internal partial class consumirComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        public WSCComu.Comunicacion Comunicacion;
        
        public consumirComunicacionResponse()
        {
        }
        
        public consumirComunicacionResponse(WSCComu.Comunicacion Comunicacion)
        {
            this.Comunicacion = Comunicacion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Estado
    {
        
        private long idField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstados", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    internal partial class consultarEstados
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSCComu.AuthRequest authRequest;
        
        public consultarEstados()
        {
        }
        
        public consultarEstados(WSCComu.AuthRequest authRequest)
        {
            this.authRequest = authRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstadosResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    internal partial class consultarEstadosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsNullable=false)]
        public WSCComu.Estado[] Estados;
        
        public consultarEstadosResponse()
        {
        }
        
        public consultarEstadosResponse(WSCComu.Estado[] Estados)
        {
            this.Estados = Estados;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface VEConsumerChannel : WSCComu.VEConsumer, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class VEConsumerClient : System.ServiceModel.ClientBase<WSCComu.VEConsumer>, WSCComu.VEConsumer
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VEConsumerClient() : 
                base(VEConsumerClient.GetDefaultBinding(), VEConsumerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.VEConsumerPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VEConsumerClient(EndpointConfiguration endpointConfiguration) : 
                base(VEConsumerClient.GetBindingForEndpoint(endpointConfiguration), VEConsumerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VEConsumerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VEConsumerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VEConsumerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VEConsumerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VEConsumerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCComu.consultarComunicacionesResponse> WSCComu.VEConsumer.consultarComunicacionesAsync(WSCComu.consultarComunicaciones request)
        {
            return base.Channel.consultarComunicacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCComu.consultarComunicacionesResponse> consultarComunicacionesAsync(WSCComu.AuthRequest authRequest, WSCComu.Filter filter)
        {
            WSCComu.consultarComunicaciones inValue = new WSCComu.consultarComunicaciones();
            inValue.authRequest = authRequest;
            inValue.filter = filter;
            return ((WSCComu.VEConsumer)(this)).consultarComunicacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCComu.consultarSistemasPublicadoresResponse> WSCComu.VEConsumer.consultarSistemasPublicadoresAsync(WSCComu.consultarSistemasPublicadores request)
        {
            return base.Channel.consultarSistemasPublicadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCComu.consultarSistemasPublicadoresResponse> consultarSistemasPublicadoresAsync(WSCComu.AuthRequest authRequest, long idSistemaPublicador)
        {
            WSCComu.consultarSistemasPublicadores inValue = new WSCComu.consultarSistemasPublicadores();
            inValue.authRequest = authRequest;
            inValue.idSistemaPublicador = idSistemaPublicador;
            return ((WSCComu.VEConsumer)(this)).consultarSistemasPublicadoresAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WSCComu.DummyResult> dummyAsync()
        {
            return base.Channel.dummyAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCComu.consumirComunicacionResponse> WSCComu.VEConsumer.consumirComunicacionAsync(WSCComu.consumirComunicacion request)
        {
            return base.Channel.consumirComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCComu.consumirComunicacionResponse> consumirComunicacionAsync(WSCComu.AuthRequest authRequest, long idComunicacion, bool incluirAdjuntos)
        {
            WSCComu.consumirComunicacion inValue = new WSCComu.consumirComunicacion();
            inValue.authRequest = authRequest;
            inValue.idComunicacion = idComunicacion;
            inValue.incluirAdjuntos = incluirAdjuntos;
            return ((WSCComu.VEConsumer)(this)).consumirComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCComu.consultarEstadosResponse> WSCComu.VEConsumer.consultarEstadosAsync(WSCComu.consultarEstados request)
        {
            return base.Channel.consultarEstadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCComu.consultarEstadosResponse> consultarEstadosAsync(WSCComu.AuthRequest authRequest)
        {
            WSCComu.consultarEstados inValue = new WSCComu.consultarEstados();
            inValue.authRequest = authRequest;
            return ((WSCComu.VEConsumer)(this)).consultarEstadosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VEConsumerPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VEConsumerPort))
            {
                return new System.ServiceModel.EndpointAddress("https://stable-middleware-tecno-ext.afip.gob.ar/ve-ws/services/veconsumer");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VEConsumerClient.GetBindingForEndpoint(EndpointConfiguration.VEConsumerPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VEConsumerClient.GetEndpointAddress(EndpointConfiguration.VEConsumerPort);
        }
        
        public enum EndpointConfiguration
        {
            
            VEConsumerPort,
        }
    }
}
